### ISSUE TITLE
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

### ISSUE THREAD

**Issue by janssenongaigui** [lmcinnes/pynndescent#101]
Getting a error when doing the query method:

`File "...", line 148, in NNDescent_matching
    matching = tree.query(..., ...)
  File ".../lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 1185, in query
    self._init_search_graph()
  File ".../lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 1032, in _init_search_graph
    self._search_graph = self._search_graph.tocsr()
  File ".../lib/python3.7/site-packages/scipy/sparse/lil.py", line 468, in tocsr
    _csparsetools.lil_get_lengths(self.rows, lengths)
  File "_csparsetools.pyx", line 109, in scipy.sparse._csparsetools.lil_get_lengths
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

Packages:
Name                    Version                   Build  Channel
- _libgcc_mutex             0.1                 conda_forge    conda-forge
- _openmp_mutex             4.5                       0_gnu    conda-forge
- abseil-cpp                20200225.2           he1b5a44_0    conda-forge
- arrow-cpp                 0.17.1          py37h1234567_8_cpu    conda-forge
- aws-sdk-cpp               1.7.164              hc831370_1    conda-forge
- backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
- boost-cpp                 1.72.0               h7b93d67_1    conda-forge
- brotli                    1.0.7             he1b5a44_1002    conda-forge
- brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
- bzip2                     1.0.8                h516909a_2    conda-forge
- c-ares                    1.15.0            h516909a_1001    conda-forge
- ca-certificates           2020.6.20            hecda079_0    conda-forge
- cachetools                4.1.1                      py_0    conda-forge
- certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
- cffi                      1.14.0           py37hd463f26_0    conda-forge
- chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
- cryptography              2.9.2            py37hb09aad4_0    conda-forge
- curl                      7.71.0               he644dc0_0    conda-forge
- decorator                 4.4.2                      py_0    conda-forge
- fastavro                  0.23.5           py37h8f50634_0    conda-forge
- gflags                    2.2.2             he1b5a44_1002    conda-forge
- glog                      0.4.0                h49b9bf7_3    conda-forge
- google-api-core           1.17.0           py37hc8dfbb8_0    conda-forge
- google-api-core-grpc      1.17.0               hc8dfbb8_0    conda-forge
- google-auth               1.17.2                     py_0    conda-forge
- google-cloud-bigquery     1.24.0             pyhc8dfbb8_0    conda-forge
- google-cloud-bigquery-core 1.24.0           py37hc8dfbb8_0    conda-forge
- google-cloud-bigquery-storage 0.7.0                         1    conda-forge
- google-cloud-bigquery-storage-core 0.7.0                    py37_1    conda-forge
- google-cloud-core         1.3.0                      py_0    conda-forge
- google-cloud-storage      1.28.1             pyh9f0ad1d_0    conda-forge
- google-resumable-media    0.5.1              pyh9f0ad1d_0    conda-forge
- googleapis-common-protos  1.51.0           py37hc8dfbb8_2    conda-forge
- grpc-cpp                  1.30.0               h9ea6770_0    conda-forge
- grpcio                    1.27.2           py37hb0870dc_0    conda-forge
- icu                       67.1                 he1b5a44_0    conda-forge
- idna                      2.10               pyh9f0ad1d_0    conda-forge
- ipython                   7.16.1           py37h43977f1_0    conda-forge
- ipython_genutils          0.2.0                      py_1    conda-forge
- jedi                      0.17.1           py37hc8dfbb8_0    conda-forge
- joblib                    0.15.1                     py_0    conda-forge
- krb5                      1.17.1               hfafb76e_1    conda-forge
- ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
- libblas                   3.8.0               14_openblas    conda-forge
- libcblas                  3.8.0               14_openblas    conda-forge
- libcurl                   7.71.0               hcdd3856_0    conda-forge
- libedit                   3.1.20191231         h46ee950_0    conda-forge
- libevent                  2.1.10               hcdb4288_1    conda-forge
- libffi                    3.2.1             he1b5a44_1007    conda-forge
- libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
- libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
- libgomp                   9.2.0                h24d8f2e_2    conda-forge
- liblapack                 3.8.0               14_openblas    conda-forge
- libllvm8                  8.0.1                hc9558a2_0    conda-forge
- libopenblas               0.3.7                h5ec1e0e_6    conda-forge
- libprotobuf               3.12.3               h8b12597_0    conda-forge
- libssh2                   1.9.0                hab1572f_2    conda-forge
- libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
- llvmlite                  0.30.0           py37h8b12597_1    conda-forge
- lz4-c                     1.9.2                he1b5a44_1    conda-forge
- ncurses                   6.1               hf484d3e_1002    conda-forge
- numba                     0.46.0           py37hb3f55d8_1    conda-forge
- numpy                     1.17.5           py37h95a1406_0    conda-forge
- openssl                   1.1.1g               h516909a_0    conda-forge
- pandas                    1.0.5            py37h0da4684_0    conda-forge
- parquet-cpp               1.5.1                         2    conda-forge
- parso                     0.7.0              pyh9f0ad1d_0    conda-forge
- pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
- pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
- pip                       20.1.1                     py_1    conda-forge
- prompt-toolkit            3.0.5                      py_1    conda-forge
- protobuf                  3.12.3           py37h3340039_0    conda-forge
- ptyprocess                0.6.0                   py_1001    conda-forge
- pyarrow                   0.17.1          py37h1234567_8_cpu    conda-forge
- pyasn1                    0.4.8                      py_0    conda-forge
- pyasn1-modules            0.2.7                      py_0    conda-forge
- pycparser                 2.20               pyh9f0ad1d_2    conda-forge
- pygments                  2.6.1                      py_0    conda-forge
- pynndescent               0.4.3                      py_0    conda-forge
- pyopenssl                 19.1.0                     py_1    conda-forge
- pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
- python                    3.7.6           cpython_h8356626_6    conda-forge
- python-dateutil           2.8.1                      py_0    conda-forge
- python_abi                3.7                     1_cp37m    conda-forge
- pytz                      2020.1             pyh9f0ad1d_0    conda-forge
- re2                       2020.06.01           he1b5a44_0    conda-forge
- readline                  8.0                  hf8c457e_0    conda-forge
- requests                  2.24.0             pyh9f0ad1d_0    conda-forge
- rsa                       4.6                pyh9f0ad1d_0    conda-forge
- scikit-learn              0.23.1           py37h8a51577_0    conda-forge
- scipy                     1.5.0            py37ha3d9a3c_0    conda-forge
- setuptools                47.3.1           py37hc8dfbb8_0    conda-forge
- six                       1.15.0             pyh9f0ad1d_0    conda-forge
- snappy                    1.1.8                he1b5a44_3    conda-forge
- sqlite                    3.32.3               hcee41ef_0    conda-forge
- threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
- thrift-cpp                0.13.0               h62aa4f2_2    conda-forge
- tk                        8.6.10               hed695b0_0    conda-forge
- tqdm                      4.47.0             pyh9f0ad1d_0    conda-forge
- traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
- urllib3                   1.25.9                     py_0    conda-forge
- wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
- wheel                     0.34.2                     py_1    conda-forge
- xz                        5.2.5                h516909a_0    conda-forge
- zlib                      1.2.11            h516909a_1006    conda-forge
- zstd                      1.4.4                h6597ccf_3    conda-forge

**Comment by liyao880** [comment]
Got similar error with pynndescent

**Comment by lmcinnes** [comment]
I have generally struggled to manage to reproduce this error, so there is clearly something at least a little subtle going on with this. I've tried moving away from use of lil matrices in general, so I would hope this would have disappeared by now. @liyao880 do you have a stack trace of where in pynndescent your current error is occuring?

**Comment by liyao880** [comment]
> I have generally struggled to manage to reproduce this error, so there is clearly something at least a little subtle going on with this. I've tried moving away from use of lil matrices in general, so I would hope this would have disappeared by now. @liyao880 do you have a stack trace of where in pynndescent your current error is occuring?

Here's the stack trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/longleaf/home/yaoli/adversarial-detection/expts/detectors/detector_proposed.py", line 513, in score
    test_stats_temp, pvalues_temp = self.test_stats_models[i].score(data_proj, labels_pred, is_train=is_train,
  File "/nas/longleaf/home/yaoli/adversarial-detection/expts/detectors/test_statistics_layers.py", line 347, in score
    nn_indices, _ = self.index_knn.query(features_test, k=self.n_neighbors)
  File "/nas/longleaf/home/yaoli/adversarial-detection/expts/helpers/knn_index.py", line 235, in query
    return self._query(data, self.index_knn[0], k)
  File "/nas/longleaf/home/yaoli/adversarial-detection/expts/helpers/knn_index.py", line 252, in _query
    nn_indices, nn_distances = index.query(data, k=k)
  File "/home/yaoli/.local/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 886, in query
    self._init_search_graph()
  File "/home/yaoli/.local/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 842, in _init_search_graph
    self._search_graph.transpose()
  File "/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/lil.py", line 437, in transpose
    return self.tocsr(copy=copy).transpose(axes=axes, copy=False).tolil(copy=False)
  File "/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/lil.py", line 462, in tocsr
    _csparsetools.lil_get_lengths(self.rows, indptr[1:])
  File "_csparsetools.pyx", line 109, in scipy.sparse._csparsetools.lil_get_lengths
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

**Comment by lmcinnes** [comment]
I'm pretty sure all the lil_matrix calls have been eliminated, so it seems odd that this should be happening. The line numbers don't correspond to the current version -- can you confirm you are on version 0.5.1?

**Comment by liyao880** [comment]
> I'm pretty sure all the lil_matrix calls have been eliminated, so it seems odd that this should be happening. The line numbers don't correspond to what I'm currently seeing in the development code -- can you confirm you are on version 0.5.1? If not then perhaps upgrading will solve the issue; if you are, then there is something deeper astray here. I'll have to see if I can reproduce this myself in any way.

Thanks! Updating to 0.5.1 removes the error.

**Comment by lmcinnes** [comment]
Excellent -- glad that worked for you.
