### ISSUE TITLE
Cannot install pynndescent=0.4.8 with numba>=0.48

### ISSUE THREAD

**Issue by dkobak** [lmcinnes/pynndescent#102]
This installation attempt:
```
conda create --name pynntest
conda activate pynntest
conda install numba=0.48.0
conda install -c conda-forge pynndescent=0.4.8
```
finds unresolvable errors and fails. I do not know why. Pynndescent does not seem to have any `<=` requirements, e.g. it specifies `numba>=0.46`. Is this expected behaviour?

To be able to install the last version of pynndescent, I need to revert to numba 0.46 (for which I need to revert to Python 3.7), which also reverts llvmlite to 0.30.0 along the way:
```
conda install python=3.7
conda install numba=0.46.0
conda install -c conda-forge pynndescent=0.4.8
```
This works.

**Comment by lmcinnes** [comment]
It looks like this was a lingering issue in the feedstock for conda-forge (and shouldn't be true of, for example, the PyPI package). I'm working to fix it now, hopefully it will be available soon.

**Comment by lmcinnes** [comment]
It should now be in place; it may take a while to propagate out to conda-forge.

**Comment by dkobak** [comment]
Thanks Leland. It works perfectly fine now. I can install 0.4.8 from conda-forge. Closing.
