### ISSUE TITLE
Default compression inconsistent documentation/value

### ISSUE THREAD

**Issue by bittremieux** [lmcinnes/pynndescent#105]
The [nnDescent constructor docstring](https://github.com/lmcinnes/pynndescent/blob/master/pynndescent/pynndescent_.py#L657) states that `compressed` is False by default, by the [default value is actually `True`](https://github.com/lmcinnes/pynndescent/blob/master/pynndescent/pynndescent_.py#L685).

I would have created a PR to fix this small inconsistency, but I don't know what the preferred behavior is.

**Comment by lsorber** [comment]
The default value is `False` currently, which aligns with the docstring.
