### ISSUE TITLE
No conversion from float32 to array(float32, 1d, C) for 'current_query', defined at None

### ISSUE THREAD

**Issue by hooori** [lmcinnes/pynndescent#107]
I installed pynndescent via `pip3 install pynndescent`. Requirements are also installed with the mentioned versions on the page. I try to run just a simple test like below:
```python
from pynndescent import NNDescent
index = NNDescent(matrix, metric="euclidean", n_neighbors=20)
print(index.query(query_data=np.array([0, 1]), k=20))
```
Matrix is defined as array of shape (n_samples, n_features).
but I get the following error:
<img width="676" alt="Screen Shot 2020-12-08 at 3 06 22 PM" src="https://user-images.githubusercontent.com/19370383/101535702-0a2bf600-3967-11eb-8246-73cef831a7c6.png">
<img width="689" alt="Screen Shot 2020-12-08 at 3 06 33 PM" src="https://user-images.githubusercontent.com/19370383/101535706-0c8e5000-3967-11eb-95e4-12fc325f3101.png">

Any suggestions to solve the issue?

**Comment by lmcinnes** [comment]
The query needs to to be a query set, rather than an individual point. Try:

```python
from pynndescent import NNDescent
index = NNDescent(matrix, metric="euclidean", n_neighbors=20)
print(index.query(query_data=np.array([[0, 1]]), k=20))
```

**Comment by hooori** [comment]
Thanks for your answer. It solved my problem. 
However, I believe `query_data=np.array([0, 1])` is an array and not an individual point. It shows sample 0 and 1 and according to the documentation it should work. Please correct me if I'm wrong. 

Thanks
