### ISSUE TITLE
Pickling does not work for compress_index()'d NNDescent objects (=> PyNNDescentTransformer not picklable by default)

### ISSUE THREAD

**Issue by frankier** [lmcinnes/pynndescent#109]
Say I try to dump a pipeline with a `PyNNDescentTransformer` object in it, I get:

```
  File "/path/to/clus.py", line XXX, in yyy
    pickle.dump(estimator, modelf)
  File "/path/to/.venv/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 929, in __getstate__
    self._init_search_graph()
  File "/path/to/.venv/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 957, in _init_search_graph
    for tree in self._rp_forest
AttributeError: 'NNDescent' object has no attribute '_rp_forest'
```

The reason is that compress_index() deletes _rp_forest, which seems to be needed by the `__getstate__` pickling logic.

**Comment by lmcinnes** [comment]
Yes, that is definitely an issue. I'll have to see what the best way to make that all work is going to be.

**Comment by lmcinnes** [comment]
I'm having trouble reproducing this -- I added some tests, but at least locally they ran fine. I'll see what the CI says about them.

**Comment by lmcinnes** [comment]
It seems like CI failed with some other errors related to changes in sklearn. I'm fixing those now, and we'll see what we get, but there is certainly something a little odd going on. In terms of what may be at issue here: somehow the ``_rp_forest`` is getting deleted *without* the ``_search_forest`` getting constructed. I can't trivially rule out that such a thing is possible via some code path, but I am struggling to generate one that makes it happen. It's definitely a little bit of a corner case, but it also definitely needs to be fixed. Any test cases you can provide would be greatly appreciated.

**Comment by frankier** [comment]
Hi, this was in 0.5.1, and I thought I'd replicated this on master too, but not sure. It seems to be fixed on the current master. Thanks!

Just for completeness here is what was broken:

```
# -*- coding: utf-8 -*-
import numpy as np
import pickle

from pynndescent import PyNNDescentTransformer
from sklearn import metrics
from sklearn.cluster import DBSCAN
from sklearn.pipeline import make_pipeline
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler


X, labels_true = make_blobs(n_samples=1000, n_features=512, centers=5, cluster_std=0.4,
                            random_state=0)

X = StandardScaler().fit_transform(X)

pipeline = make_pipeline(
    PyNNDescentTransformer(n_neighbors=256),
    DBSCAN(eps=0.3, min_samples=10),
)
labels = pipeline.fit_predict(X)

print("Adjusted Rand Index: %0.3f"
      % metrics.adjusted_rand_score(labels_true, labels))

pickle.dump(pipeline, open("pipeline.pkl", "wb"))
```
