### ISSUE TITLE
scanpy.pp.neighbors with pynndescent 

### ISSUE THREAD

**Issue by victorpara1407** [lmcinnes/pynndescent#124]
Hi,

in the documentation available in the scanpy website there is a side note suggesting that pynndescent can improve the performance of the scanpy.pp.neighbors computation when umap is chosen as methods. My question is how can I link these two  functions? how can I tell the program that I want to combine them to increase the performance?

Warm regards,

Thanks

**Comment by lmcinnes** [comment]
I am unclear of the method that scanpy uses to handle this, so you would be best to check with them to be sure, but in the case of umap there is simply a check if pynndescent is installed (or, at least, importable) and it will automatically use it if it is. Thus, in principle, all you need to do is install pynndescent in the same python installation that has umap (and scanpy).
