### ISSUE TITLE
is `pruning_degree_multiplier` ever used?

### ISSUE THREAD

**Issue by jamestwebber** [lmcinnes/pynndescent#159]
I have been running into some cases where NNDescent doesn't find all the neighbors I asked for, so I was reading the docs about how to tweak parameters. When I search the codebase, I can't see where`pruning_degree_multiplier` is actually used by anything. Is it hiding somewhere, or is this just deprecated behavior?

If the latter, happy to make a PR to remove this from the code and docs, as it's rather confusing.

**Comment by jlmelville** [comment]
I think it is used (or it is supposed to be), but there is a change in the field name to `prune_degree_multiplier` so it might not be getting passed around properly.

**Comment by jamestwebber** [comment]
Ohhh it gets its name changed to `prune_degree_multiplier` right before it gets used, I missed that! Okay this can get closed then. Although the naming is very confusing 😂
