### ISSUE TITLE
RFC: Deprecate support for Python 3.6

### ISSUE THREAD

**Issue by jamestwebber** [lmcinnes/pynndescent#161]
Python 3.6 is [no longer supported by numpy](https://numpy.org/devdocs/release/1.20.0-notes.html), for a while now. As of this month it is [no longer receiving security fixes](https://pythonspeed.com/articles/stop-using-python-3.6/). It is probably time to deprecate support for it in this package. Or it could simply be dropped in the next release, since the previous versions will remain available.

This does not change any code immediately, but an official decision would allow for using newer language features, like delayed type annotations ([PEP 563](https://www.python.org/dev/peps/pep-0563/)).

**Comment by lmcinnes** [comment]
I'm all on board for deprecating 3.6 support. Type annotations would likely not go astray; I will have to check how they play with numba before throwing in too many.

**Comment by jamestwebber** [comment]
> I'm all on board for deprecating 3.6 support. Type annotations would likely not go astray; I will have to check how they play with numba before throwing in too many.

I don't think numba pays attention to them–neither does Python itself, for that matter. I use type-hints in some `njit`ed code and it doesn't seem to care. I don't specify values in the decorator as much as you do, though.

One reason I mentioned them was because I was looking at the documentation for #160, and I know Sphinx can read type hints if they're present (at least with some formatting flavors). Although it is sometimes difficult to write useful hints when the input is potentially a complicated object (like "something that turn into an `ndarray`"). Recent python versions have been making things easier–with 3.7 it's tricky, with 3.6 it's a pain.

**Comment by lmcinnes** [comment]
You certainly have more experience and expertise with this than me, so I would welcome any type-hinting you wanted to add.

**Comment by jamestwebber** [comment]
Done in https://github.com/lmcinnes/pynndescent/commit/36181e934eca81717ce0594d60c7a78fea17c75d
