### ISSUE TITLE
NNDescent.update_with_changed_data needs improvements

### ISSUE THREAD

**Issue by Petkomat** [lmcinnes/pynndescent#187]
For example, when _all_ data are updated, the code does not work.

Next, the code for the method could probably be improved  (possibly by removing init_kwargs, and making it more efficient).

_Originally posted by @Petkomat in https://github.com/lmcinnes/pynndescent/issues/185#issuecomment-1138536612_

**Comment by Petkomat** [comment]
Tried to merge previously existing `update` methods and [wrote only one](https://github.com/lmcinnes/pynndescent/blob/7f7a6436bdcca652d1c89fe34e096f5944b264f7/pynndescent/pynndescent_.py#L1740).

The [tests for this](https://github.com/lmcinnes/pynndescent/blob/7f7a6436bdcca652d1c89fe34e096f5944b264f7/pynndescent/tests/test_pynndescent_.py#L528) mostly pass (21/24), however, we stay under the 95% accuracy threshold in the data case 3 (for all three metrics), when
- there is no fresh data,
- only a small portion of existing data is updated.

Basicall, the code follows the previous `update(X)` method (as written [here](https://github.com/lmcinnes/pynndescent/blob/d282266141bcc19fa3dfeef4ad4186468a84a50b/pynndescent/pynndescent_.py#L1707)):

- update the data (update the previously existing lines, append the fresh data),
- do the descent etc.

I would assume that the problematic test case is actually "easier" than some others (when, e.g., also fresh data appear). Am I doing something wrong?

**Comment by lmcinnes** [comment]
I'm not sure, I'll have to take a look. It could just be that the process is a little stochastic and noisy, and we happen to be hitting some bad cases. In that sense the answer may be to weaken the threshold. How far under the 95% are we?

**Comment by Petkomat** [comment]
It turns out, I did something wrong: `ns, ds = self.neighbor_graph` did not change `self._neighbor_graph`. Will do a PR, test now pass.

**Comment by Petkomat** [comment]
Resolved with 7884b09ed4e7e720b032c89916b6096c86f53927
