### ISSUE TITLE
remove python 2.7 support?

### ISSUE THREAD

**Issue by jlmelville** [lmcinnes/pynndescent#19]
I was going to have a go at adding some CI support to pynndescent: travis for linux (and maybe mac os x?) and also have a look at appveyor for Windows.

The python 2.7 build is failing because the multithreading tests need `concurrent.futures`. Is python 2 support going to be removed or does https://pypi.org/project/futures/ need to be added to `setup.py`?

**Comment by lmcinnes** [comment]
I have no expectation of python2 support anymore, so let's consider it essentially removed for now. I'll update the setup.py to reflect that.

**Comment by jlmelville** [comment]
Looks good to me. Closing.
