### ISSUE TITLE
Correlation function needs reconsideration

### ISSUE THREAD

**Issue by DipeshNiraula** [lmcinnes/pynndescent#195]
Currently the correlation function returns:       

577  return 1.0 - (dot_product / np.sqrt(norm_x * norm_y))

If I understand correctly this is an attempt to invert the correlation similarity value to dissimilarity distance metric. However, since values near to both the lower and upper bounds of the correlation coefficient, [-1, 1], indicates strong similarity, this is problematic. 

In the current form,
Negative correlation coefficient, which ranges from 0 to -1, yields distance ranging from 1 to 2 and 
Positive correlation coefficient, which ranges from 0 to 1, yields distance ranging from 1 to 0. 

The distance in this form cannot be ordered correctly as similarity decreases from 0 to 1 but then increases from 1 to 2.

One way of correcting would be to put an absolute value: 1 - |corr|. Such distance metric would not be able to differentiate between positive and negative association, but it would make the distance monotonic wrt similarity.

May be the negative and positive correlation can be treated separately when assigning the nearest neighbor.

**Comment by jamestwebber** [comment]
Two variables being perfectly anti-correlated (`r = -1`) implies a relationship, but it definitely doesn't imply similarity.

The current implementation is the definition of [Pearson's distance](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Pearson's_distance).

You could certainly implement `1 - |corr|` as a custom metric if you wished, if that makes sense for you.

**Comment by DipeshNiraula** [comment]
Yes, it does. Both 1 and -1 Pearson correlation coefficient corresponds to cosine similarity of 1(or near 1), at least for the positive space. Because corr coeff is simply a cosine similarity in the sample space centered at the mean.
 
Yes, I understand the attempt to convert correlation into distance by subtracting it from 1. However, this does not work for correlation coefficient. 

Currently I am defining |1-corr| but I think I will just stick to 1-cos instead.
[corr_vs_cos.pdf](https://github.com/lmcinnes/pynndescent/files/9200845/corr_vs_cos.pdf)

**Comment by jamestwebber** [comment]
> Yes, it does. Both 1 and -1 Pearson correlation coefficient corresponds to cosine similarity of 1(or near 1), at least for the positive space.

??? This just isn't true

**Comment by DipeshNiraula** [comment]
Thanks James, I just checked the cor is -1 but the cos is 0.571, but both cor and cos between np.arange(10) and np.arange(10) was 1.  So, looks like cos distance does differentiate between positive and negative correlation, but considers positive correlation to be more similar than negative correlation. Both positive and negative correlation are similar (\in [0,1]) wrt cosine.

Anyways, the argument about 1-cor distance still holds. For negative correlation, the distance is large, and when pydescent finds NN its will only consider neighbor with positive cor and neglect neighbor negative cor.  However, in reality finding a strong negative correlation is just as important.

**Comment by jamestwebber** [comment]
> Anyways, the argument about 1-cor distance still holds. For negative correlation, the distance is large, and when pydescent finds NN its will only consider neighbor with positive cor and neglect neighbor negative cor. However, in reality finding a strong negative correlation is just as important.

This will always be application and data-dependent, though. Sometimes it's important, sometimes it isn't, sometimes it's important but does not imply they are similar items that should be linked in a kNN graph. It depends on context, which is beyond the scope of a generic kNN package.

This package can't redefine "correlation distance" to mean something different from how it is defined in the literature and other packages. It is simple to write your own metric if you want your distances to work that way, but it won't be correlation distance.

**Comment by DipeshNiraula** [comment]
Well in that case, it might be worth including one sentence on this issue: Defining correlation "distance" as 1-corr does not treat negative correlation as nearest Neighbour.
