### ISSUE TITLE
Add pynndescent to ann-benchmarks?

### ISSUE THREAD

**Issue by maumueller** [lmcinnes/pynndescent#2]
Hi Leland,

we are running a benchmark of nearest neighbor search algorithms on https://github.com/erikbern/ann-benchmarks. We would be very interested in adding pynndescent to the benchmark! (We have some other knn graph algorithms in there as well.)

All we need is 
- a wrapper to know how to build the index and run queries (such as https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/algorithms/annoy.py)
- a way to install pynndescent inside a docker container, as exemplified here https://github.com/erikbern/ann-benchmarks/blob/master/install/Dockerfile.annoy
- a set of parameters that should be tested in the benchmark (inside https://github.com/erikbern/ann-benchmarks/blob/master/algos.yaml).

Of course, it would be easiest if you could provide this information via a pull request to our repo, but we can of course help you out with it as well. :-) 

What do you think?

Best,
Martin

**Comment by lmcinnes** [comment]
Hi Martin,

I am familiar with your ann-benchmarks -- it's excellent work! I would be happy to have pynndescent included. Right now the library is pretty young, so I'll probably iron out some on the kinks before I try to get it included. Some other caveats: it probably won't compare that well with some of the high performance libraries like nmslib and kgraph (which it uses essentially the same underlying algorithm as). Mostly I just wanted something that I could easily use "out of the box" with python.

Once I get a little further along with the library itself I'll be sure to submit a pull request with the required additions for pynndescent. Thanks for you interest!

**Comment by maumueller** [comment]
Hi again,

sounds great, please keep me up-to-date. 

I agree that it might not be as performant, but some people are clearly interested in a ‘pure’ python implementation. Would be interesting to see how they would compare.
