### ISSUE TITLE
how to create a plot for HNSW

### ISSUE THREAD

**Issue by jianshu93** [lmcinnes/pynndescent#248]
Dear pynndescent team,

Just curious how the animate here (https://pynndescent.readthedocs.io/en/latest/how_pynndescent_works.html) was created. I want to create a similar one for HNSW (another nearest neighbor graph search algorithm) with hierarchical layers. I understand the algorithm itself is different but at least a similar idea can be used to create the plot?

Best,
Jianshu

**Comment by lmcinnes** [comment]
Unfortunately the notebooks I had for making those animations were lost in a hard drive crash. They were just generated using the matplotlib animation tools however, and didn't involve anything too fancy -- just stepping through the algorithm and updating the plots accordingly. I even did an NSW animation which was [in this talk at 33 minutes in](https://youtu.be/OvT2NY_FV_g?t=1989). Unfortunately that animation was lost along with the notebooks (the other animations got mirrored elsewhere).

**Comment by jianshu93** [comment]
Thanks anyway, I can imagine for HNSW, in a certain layer, the search path should be similar but faster since the long range links will speed up the search but for KNN, there are no long range links. 

Best,
Jianshu
