### ISSUE TITLE
AttributeError: maximum not found

### ISSUE THREAD

**Issue by moinnadeem** [lmcinnes/pynndescent#3]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-31bf7e4c72a2> in <module>()
----> 1 nndescent = NNDescent(all_sets)

/usr/lib/python2.7/site-packages/pynndescent/pynndescent_.pyc in __init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_level, tree_init, random_state, algorithm, max_candidates, n_iters, delta, rho)
    551         self._search_graph.rows = self._neighbor_graph[0]
    552         self._search_graph.data = self._neighbor_graph[1]
--> 553         self._search_graph = self._search_graph.maximum(
    554             self._search_graph.transpose()).tocsr()
    555         self._search_graph = prune(self._search_graph,

/usr/lib64/python2.7/site-packages/scipy/sparse/base.pyc in __getattr__(self, attr)
    398             return self.getnnz()
    399         else:
--> 400             raise AttributeError(attr + " not found")
    401 
    402     def transpose(self):

AttributeError: maximum not found
```

Trying to build it on a dense numpy matrix of shape (4890980, 128)

**Comment by lmcinnes** [comment]
I think the issue here is that I may be taking advantage of newer scipy
features than I managed to put into the requirements. The long terms
solution is probably for me to update the requirements, the short term
solution for you would be to consider updating to a newer scipy release if
you can. I'll try to get the requirements updated soon.

**Comment by moinnadeem** [comment]
Do you know what version of scipy + numpy you're running, so I know what to upgrade to? Thanks!

**Comment by lmcinnes** [comment]
I'm on 1.0 and 1.13 and that seems to work, I'm pretty sure it worked on
earlier versions as well, but I can't be sure. I haven't had the time to
set up the proper test infrastructure to have proper CI on different
versions to make sure everything works properly. Sorry about that -- other
projects have been dominating my time lately.

**Comment by moinnadeem** [comment]
No worries on that, I think that's fine. I'm on 1.1.0, but when I run scipy.__version__, I get 0.12.1. Is this normal?

**Comment by lmcinnes** [comment]
No -- that may be the issue; somehow the kernel you are running is not
finding the right scipy. I'm not sure how that is occuring, but you may
want to check through environments etc.

**Comment by moinnadeem** [comment]
Upgrading SciPy fixed it!
