### ISSUE TITLE
binary pairwise distance issue with sklearn 0.21.0

### ISSUE THREAD

**Issue by jlmelville** [lmcinnes/pynndescent#44]
Just a heads-up: today the travis-ci builds updated to a new version of sklearn, 0.21.0,  (previously it was 0.20.3), and some binary distance tests are now failing. I think it's a bug in sklearn.

I have filed an issue: https://github.com/scikit-learn/scikit-learn/issues/13853

Depending on the resolution, the versions specified in `setup.py` and `requirements.txt` may need modifying.

Edited to note that this only affects test code.

**Comment by lmcinnes** [comment]
Thanks -- looks like they have fixed it upstream. Hopefully the patch release will be along soon.

**Comment by jlmelville** [comment]
0.21.1 is out with the fix, and travis-ci has picked up the change, so we are back in business.
