### ISSUE TITLE
Release pynndescent 0.3.0

### ISSUE THREAD

**Issue by tomwhite** [lmcinnes/pynndescent#48]
It would be good to do a new release. The last release was 0.2.1 in July last year (https://pypi.org/project/pynndescent/).

**Comment by jlmelville** [comment]
I ran [pyroma](https://github.com/regebro/pyroma) (via [Prospector](https://github.com/PyCQA/prospector)), a linting tool specifically for `setup.py`, and it suggested a few minor changes that might be worth including. I will supply a PR later today.

**Comment by tomwhite** [comment]
Thanks @jlmelville!

**Comment by lmcinnes** [comment]
Thanks @tomwhite and @jlmelville for all the work you have both put into this recently -- it has been greatly appreciated. I really hope to get some time soon to go through and properly catch up with everything and start adding a few bits and pieces (multi-threaded trees, dask support, etc.) In the meantime, yes, this is definitely worthy of a 0.3 release -- I'll wait for James to make his changes, and try and get it done in the next day or so.

**Comment by tomwhite** [comment]
Thanks @lmcinnes.

Re dask support, I have got a branch that I wrote a while ago. I'll post it soon.

**Comment by tomwhite** [comment]
Before we release this I was thinking it would be good to be sure that the API for running in threaded mode is what we want. I've started looking at joblib to see if we can use that.

**Comment by lmcinnes** [comment]
I'm happy with the current state, but understand if you want to address a few of the remaining joblib related bits and pieces first (alternatively we can add those in a 0.3.1 as needed). Let me know.

**Comment by tomwhite** [comment]
I think it's worth removing `chunk_size` from the API for `NNDescent` or at least making it optional. I will submit a PR. (Other bits and pieces can wait for a point release.)

**Comment by tomwhite** [comment]
Thanks for releasing 0.3.0 @lmcinnes!

**Comment by lmcinnes** [comment]
Glad to see all your and James' work make it out into a release.
