### ISSUE TITLE
Basic test fails

### ISSUE THREAD

**Issue by MilesCranmer** [lmcinnes/pynndescent#5]
Hey @lmcinnes, I'm trying out this package but I can't seem to get an example like on the README working. I looked at the ann-benchmark code for an example and I noticed that other keyword arguments are supplied, so maybe the default example needs more parameters?

My example test is:
```python
        data = np.random.normal((5, 4), (6, 0.3), size=(15, 2))
        index = NNDescent(data)

        print(index.query(np.array([6.00, 4.00]), k=15))
```

The error this gives is:

```python
E
======================================================================
ERROR: test_basic_load (test.TestAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/ceph/users/mcranmer/pynndescent/test.py", line 8, in test_basic_load
    index = NNDescent(data)
  File "/mnt/ceph/users/mcranmer/pynndescent/pynndescent/pynndescent_.py", line 511, in __init__
    for i in range(n_trees)
  File "/mnt/ceph/users/mcranmer/pynndescent/pynndescent/pynndescent_.py", line 511, in <listcomp>
    for i in range(n_trees)
  File "/mnt/ceph/users/mcranmer/pynndescent/pynndescent/rp_trees.py", line 310, in flatten_tree
    hyperplanes = np.zeros((n_nodes, tree.hyperplane.shape[0]),
AttributeError: 'NoneType' object has no attribute 'shape'

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
```

I tried tinkering around with the tree object to see if I could set it to just be
```
hyperplanes = np.zeros((n_nodes))
```
if the hyperplanes are None, but this of course blew up. Do you know what the issue could be?

I am on python 3.6 with:

sklearn: 0.20.0
numba: 0.38.

Cheers,
Miles

**Comment by lmcinnes** [comment]
The short answer is that the dataset is too small, and that's causing the
RP-trees to fail. In practice I should probably handle that case more
elegantly and either work without the trees, or simply give a more useful
error. In the meantime try increasing the size to something rather larger
than 15 and you should be fine.

**Comment by MilesCranmer** [comment]
Yep, that was it, thanks! The dataset was just too small.

**Comment by danielsnider** [comment]
+1 
A warning or error message would be helpful in this case.
