### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by dkobak** [lmcinnes/pynndescent#6]
Does `pynndescent` support sparse matrices (i.e. `scipy.sparse` objects)? I think UMAP does, so I guess this package also does, but can you confirm? If yes, maybe mention this feature somewhere in `README`? Currently it does not contain the word "sparse".

Also, if yes, do you have any idea how competitive it is to other existing libraries for approximate nearest neighbours on sparse data? I know about `ann-benchmarks` but it only seems to include non-sparse libraries, so I am not sure how to get an overview of what there is available in terms of sparse support. What I know found was https://github.com/RUSH-LAB/Flash and https://github.com/facebookresearch/pysparnn, but I guess there is more.

I am thinking of huge and very sparse text-based datasets, with millions of samples and millions of features.

**Comment by lmcinnes** [comment]
At the current time, yes. Hopefully I will get that fixed at some point.
