### ISSUE TITLE
Store distances as float32?

### ISSUE THREAD

**Issue by tomwhite** [lmcinnes/pynndescent#60]
Currently distances are stored in a heap as `np.float64` types. In threaded mode an array of heap updates is stored, also as `np.float64`, which can be very large for large datasets (the number of updates is proportional to N * K * K, where N is num rows, K is num neighbors). It would halve memory usage if the heap could be represented as a `np.float32`.

Interestingly, the data array is already converted to `np.float32` in the `NNDescent` constructor, so changing distances `np.float32` should not result in a loss of precision.

The return array of distances is `np.float64`, but it may be possible to use `np.float32` internally for distance calculations and convert to `np.float64` before returning.

@lmcinnes I wonder if you have any thoughts about this, including around compatibility (in UMAP)?

**Comment by lmcinnes** [comment]
I think for these purposes it should be fine to convert to float32, and I don't see that as having any major impact on UMAP.
