### ISSUE TITLE
Any plans to release on conda-forge?

### ISSUE THREAD

**Issue by pavlin-policar** [lmcinnes/pynndescent#64]
Are there any plans on releasing this package on conda-forge? As it stands, it's impossible to include this package in anything that uses conda-forge as a build system, since they only allow depending on other conda packages.

**Comment by lmcinnes** [comment]
There are plans -- I just haven't gotten to them yet. I'm pretty busy at the moment, but hopefully in the next few weeks I can get this done.

**Comment by lmcinnes** [comment]
This was fortunately easier than anticipated and the conda-forge team were pretty quick at getting everything fixed up and merged so here we are: https://github.com/conda-forge/pynndescent-feedstock

**Comment by pavlin-policar** [comment]
That's wonderful! Thanks for such a quick response.
