### ISSUE TITLE
n_jobs for PyNNDescentTransformer

### ISSUE THREAD

**Issue by jlevy44** [lmcinnes/pynndescent#69]
I saw that n_jobs is a parameter for NNDescent but not the transformer. Can you add number of jobs to the transformer if possible? Thanks!

**Comment by jlevy44** [comment]
Unless if this is automatic. I do see a lot of threads. Perhaps as had been mentioned, maybe making it multiprocess through a dask scheduler

**Comment by lmcinnes** [comment]
I don't have time to get to it right now, but I suspect it is not hard -- I would happily accept a PR if you have time to submit one.

**Comment by lmcinnes** [comment]
As to the use of dask -- I believe the threading is now handled by joblib which can optionally use dask as a backend, so from a multi-threading perspective we are using dask (or can be using dask). The more tricky dask option would be to support out-of-core or distributed computation on arrays too large for memory on a single compute node of a cluster. That requires a little more work.

**Comment by jlevy44** [comment]
I see, thanks for the discussion. I may not have the time now to PR but will keep this in mind
