### ISSUE TITLE
No tag for 0.4.0

### ISSUE THREAD

**Issue by toddrme2178** [lmcinnes/pynndescent#89]
There is no tag for version 0.4.0.  Tags are useful for people who want to use the exact source as found on github, rather than the files manually selected for sdists.  

This is a particular issue for me since I am trying to package pynndescent for openSUSE, but this is difficult without a license file in the sources, and there is no source for 0.4.0 that has the license file.

**Comment by lmcinnes** [comment]
I'll tag a 0.4.1 and then push it up to PyPI. Is that sufficient?

**Comment by toddrme2178** [comment]
Great, thanks!

**Comment by jondo** [comment]
Seems this can be closed.
