### ISSUE TITLE
NumbaPendingDeprecationWarning (type 'reflected list')

### ISSUE THREAD

**Issue by dkobak** [lmcinnes/pynndescent#92]
Just installed pynndescent 0.3.3 and got this warning:

```
/home/localadmin/anaconda3/lib/python3.7/site-packages/numba/ir_utils.py:1959: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'forest' of function 'initialise_search'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "../../../../anaconda3/lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 72:
@numba.njit()
def initialise_search(
^
```

Everything still works but I thought I'd still raise it here.

**Comment by lmcinnes** [comment]
Thanks -- that was among the issues that pushed things to the rewrite that went into 0.4.x; The newer versions have fixed this issue, among several other things.

**Comment by dkobak** [comment]
Oh damn - I am so sorry! I did not realize I installed a previous version!! Arrgh. No idea how this happened, I used conda on a new machine and that's what I got. Very strange. Closing this.
