### ISSUE TITLE
Understanding `query`weird results

### ISSUE THREAD

**Issue by dawe** [lmcinnes/pynndescent#97]
Hi all, 
I'm trying to understand how pynndescent works, in particular querying the index. First of all, I generate a random dataset and build a graph on it:

```python
>>> data = np.random.randint(1, 1000, 50000).reshape((1000, 50))
>>> index = NNDescent(data)     
```
If I got it right, `index` has a property storing all the neighbors (and distances): `index.neighbor_graph`. As an example I checked the first two entries

```python
>>> index.neighbor_graph[0][:2]
array([[  0, 811, 566, 710, 729, 369, 654, 872, 989, 624, 435, 992, 269,
         17, 346],
       [  1, 759, 242, 904, 679, 758, 915, 441, 238,  -1,  -1,  -1,  -1,
         -1,  -1]])
```
I thought `index.query()` should report the same results, but

- querying with a list raises an error
```python
>>> index.query([0, 1]) 
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No conversion from float32 to array(float32, 1d, C) for 'current_query', defined at None
```
- I tried with a 2d list and 
```python
>>> index.query([[0], [1]]) 
(array([[971, 971, 971, 971, 971, 971, 971, 971, 971, 971],
        [971, 971, 971, 971, 971, 971, 971, 971, 971, 971]], dtype=int32),
 array([[inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]], dtype=float32))
```
So, my questions are:
- what am I doing wrong in querying the index?
- can I simply use `index.neighbor_graph` data to build a graph?

**Comment by dkobak** [comment]
1) Shouldn't `query()` take the data vectors as input, not the index numbers? So if you want to get the neighbors of the vectors in `data`, then I think you should be running `query(data)`.

2) Yes, `index.neighbor_graph` contains the kNN graph, so you don't need to run query() at all for this. See https://twitter.com/leland_mcinnes/status/1213966305772089345

**Comment by dawe** [comment]
Now I see, thank you. So, query should be used to approximate search of new data in a index, that was unclear to me.
This is even better than I thought

**Comment by dkobak** [comment]
Yes, exactly, `query()` should be used for new data points.

So should this issue be closed then? Or do you want to have an official confirmation from Leland first? :)
