### ISSUE TITLE
Conda package issue

### ISSUE THREAD

**Issue by ekerazha** [lmcinnes/pynndescent#98]
When I try to install the pynndescent conda package (from conda-forge)

`conda install -c conda-forge pynndescent`

conda tries to install the old 0.3.3 version from the official anaconda repository (instead of conda-forge)

If I manually download the pynndescent package from conda-forge and I try to install it from the local file, it says that there are conflicts.

It looks like the pynndescent package in conda-forge is somewhat incompatible with the Anaconda base install.

**Comment by lmcinnes** [comment]
That's possible, but unfortunately out of my control. Conda-forge does all the building and dependencies around these things themselves. The most likely source of conflict is in numba, llvmlite, or the tbb libraries. You can try explicitly upgrading them from the Anaconda base repository first.

**Comment by ekerazha** [comment]
I upgraded everything with

`conda update --all`

Unfortunately I still can't install the pynndescent conda-forge package.

At the moment I'm just using the pypi package instead of the conda one

**Comment by lmcinnes** [comment]
They are equivalent, so it should be fine. I'll see if I can figure out what the issues with the conda-forge version are, but I'm afraid I can't make too many promises on that front.

**Comment by ekerazha** [comment]
It looks ok with the latest Anaconda/pynndescent versions.
