### ISSUE TITLE
-1 entries in neighbor_graph

### ISSUE THREAD

**Issue by dkobak** [lmcinnes/pynndescent#99]
I get some `-1` entries in the kNN graph when I build it on a sparse matrix with cosine distance. Is this intentional? Does -1 mean X.shape[0]-1? When I run `query(X)`, I don't get any negative elements. E.g.:

```
X = scipy.sparse.csr_matrix(np.random.randn(10000,1247)>3)
nn = pynndescent.NNDescent(X, metric='cosine', n_neighbors=15)
```

Now `nn.neighbor_graph[0]` has some values equal to -1 but `nn.query(X, k=15)[0]` does not.

Update: Forgot to say that I do get a warning "UserWarning: Failed to correctly find n_neighbors for some samples.Results may be less than ideal. Try re-running withdifferent parameters." from `NNDescent`. Maybe that's what -1 indicate? But then `query()` does not return any negative elements and does not complain. How should one approach this?

**Comment by dkobak** [comment]
So looking into it a bit more, it seems what whenever a row in `neighbor_graph` contains `-1` values, the corresponding `query(X)` row is meaningless and contains one element (always the same) repeated 15 times. And whenever a row in `neighbor_graph` does not contain `-1` values, the corresponding `query(X)` row looks fine.

So I assume that `-1` means that NNDescent failed as per `UserWarning` and subsequent `query` returns meaningless results for these points.

This happens with my real (non-simulated) data, but at the same time I can run UMAP on it (same metric, same number of neighbors) and it outputs something that appears sensible. So what does UMAP do with the points that NNDescent fails to identify neighbors of?

**Comment by lmcinnes** [comment]
Any -1's are ignored by UMAP, so we just end up with fewer than expected neighbors in those cases. Generally this means those points end up being outliers.

**Comment by dkobak** [comment]
Oh I see. Thanks. The warning text is 

> UserWarning: Failed to correctly find n_neighbors for some samples.Results may be less than ideal. Try re-running withdifferent parameters.

Is there a specific advice on which parameters one could try to adjust?

I get some points (using n_neighbors=15) with all 15 values equal to -1, so no neighbors of these points could be found. It feels like it is a bit dangerous to continue with UMAP/tSNE based on such a kNN graph.

**Comment by dkobak** [comment]
For your information, I've been looking at this dataset: https://johnhw.github.io/umap_primes/index.md.html. Turns out, this (all neighbors `-1`) happens for around 10% of points. It seems these are mostly prime numbers and UMAP mostly keeps them where they were at initialization.

**Comment by dkobak** [comment]
I see. This makes sense. Okay, I guess this is not an issue with Pynndescent, so I'm closing it.

**Comment by dkobak** [comment]
Hey Leland, has anything changed in the recent version of `pynndescent' regarding this behaviour? I updated to the last version and noticed that I do not get any `-1' values in the index anymore, using the same data and code as before.

**Comment by lmcinnes** [comment]
I don't believe anything changed in terms of how missing entries are handled. There were some changes in how cosine gets computed that makes it less likely to fail to find neighbors.

**Comment by dkobak** [comment]
I see, thanks. It works very effectively: e.g. in the prime factorization dataset I don't get any single -1 anymore out of N=100,000.

**Comment by lmcinnes** [comment]
Indeed; they may not be the best neighbors, but they are what can be found.
